### ISSUE TITLE
Default flags

### ISSUE THREAD

**Issue by Mikulas** [nextras/static-router#4]
I usually work with https by writing something along these lines:

```php
if ($context->getParameters()['tls'])
{
	Route::$defaultFlags |= Route::SECURED;
}
```

Since there might be multiple `StaticRouters` in one app (eg. one way homepage, the main static router, one for each subdomain etc.), it's fail prone to append the secured flag to each `StaticRouter`.

Proposal:

 - a/ use flags from `public static Route::$defaultFlags`
 - b/ add independent `public static StaticRouter::$defaultFlags`

either one solves this problem. The second solution is academically better since router is only an interface and the the router classes are not linked in any way and the flags can be defined simply enough anyway:

```php
StaticRouter::$defaultFlags = Route::$defaultFlags = Route::SECURED;
```

**Comment by JanTvrdik** [comment]
I really don't like `Route::$defaultFlags` because it's static evil and I [don't use it](https://github.com/fitak/fitak/blob/c5a24a611144af99056655b700c224793279dc80/app/misc/RouterFactory.php).

If passing the secured flag manually to each router bothers you, you may

A) Use composition – write wrapping router (see https://github.com/nette/application/pull/43 for inspiration) which would enforce the flag.
B) Use inheritance, e.g.

~~~php
class SecuredStaticRouter extends StaticRouter
{
    public function __construct(array $routingTable, $flags = 0)
    {
        parent::_construct($routingTable, $flags | self::SECURED);
    }
}

**Comment by JanTvrdik** [comment]
Therefore it is wontfix unless @hrach would **strongly** disagree with me.

**Comment by Mikulas** [comment]
Decorator does not solve the issue though, that is as repetitive as the flag itself.


Fair enough, extending the class is ok. 👌

**Comment by JanTvrdik** [comment]
Decorator solves the issue because you may use one decorator for thousand routers.

**Comment by hrach** [comment]
I'm ok with not solving this. I consider this as bad design of nette Route and StaticRouter too. This router should accept both http & https by default (any protocol in fact). Constructing URL would use current protocol. Specialization should be used when needed - in mask, another parameter in static router respectively. No need for flags. Something like forcing user to use https would/should be done on server layer.

**Comment by JanTvrdik** [comment]
> Constructing URL would use current protocol.

Which would not work if you want to have only certain page under HTTPS. I personally think that you should always use HTTPS for entire web, but I also don't think that framework should force such restriction.

**Comment by hrach** [comment]
> Which would not work if you want to have only certain page under HTTPS. I personally think that you should always use HTTPS for entire web, but I also don't think that framework should force such restriction.

That would work, because you would be able provide https constaint. Something like

```php
$router[] = new Route('https://%domain%/%basePath%/admin/<presenter>/<action>[/<id>]', array(
	'module' => 'Host',
	'presenter' => 'Homepage',
	'action' => 'default',
));
```
