### ISSUE TITLE
Release 2.0 ?

### ISSUE THREAD

**Issue by vojtechmares** [nextras/static-router#7]
Hi, I just started working on Skynette and I imidately ran into an issue - `nextras/static-router` is only for Nette 2.4.

Last 2.0 release candidate (RC2) was released in February, can you please release 2.0 ?

Or does it still need some final touches? If so, what kind so I can do them and send PR.

I can't use unstable release :/

**Comment by hrach** [comment]
Rather than a need for final touches we'd like to hear some feedback. So feel free answer here if the RC works correctly work for you and we will tag the stable release :)

**Comment by vojtamares** [comment]
@hrach after a short discussion, I am using the `2.0.0rc2`, my usage is very simple so far and I had no issues or errors.

My whole router factory class:
```php
final class RouterFactory
{
	use Nette\StaticClass;

	public static function createRouter(): RouteList
	{
	    $router = new RouteList();

	    $router[] = new StaticRouter(['Homepage:cz' => 'index.php'], StaticRouter::ONE_WAY);

	    $router[] = new StaticRouter([
		    'Homepage:en' => 'english',
		    'Homepage:cz' => '',
		    'About:en' => 'about-us',
		    'About:cz' => 'o-nas',
		    'Contact:en' => 'contact',
		    'Contact:cz' => 'kontakt',
            ]);

	    return $router;
	}
}
```

So far so good, I do not think that I will anything else with the router, so I might not be the best tester ever due to my usecase.

**Comment by chemix** [comment]
I use RC2 with NF3 for more than 4 months and without issues. 👍

**Comment by JanTvrdik** [comment]
Stable version has been released.
